### ISSUE TITLE
Last Stand + lifegiving gem under wrong formula

### ISSUE THREAD

**Issue by timgurto** [ServerProject/Phoenix_1.12.1_Issue_tracker#1150]
The warrior ability Last Stand correctly adds 30% of base HP for 20 seconds.  When the 20 seconds expire, though, that extra amount of health should be deducted.  Currently it removes the extra from the base hp, but fails to take away the actual health that was added.

If you 50/100HP, Last Stand should increase it to 80/130 (both increased by 30% of max HP), then reduce the max back to 100, and deduct 30 from the current HP, leaving the player with 1 health if below 30% of your max HP.

Currently, it increases correctly to 80/130, but when the time expires it maintains the health, at 80/100.

Until it's fixed, it effectively acts as a heal.

**Comment by ivid** [comment]
Fixed, coming soon on PTR.

**Comment by Zykes** [comment]
Oh great, only four years too late. =P

**Comment by ivid** [comment]
Re-fixed.

**Comment by anaaz** [comment]
Fix applied to Live on 23/06/2016 Patch 12
