### ISSUE TITLE
[Quest] Gnomeregan - The Only Cure is More Green Glow

### ISSUE THREAD

**Issue by Phatcat** [ServerProject/Phoenix_1.12.1_Issue_tracker#2687]
This quest is somewhat bugged. It is true that you aren't a 100% sure on getting the High Potency Radioactive Fallout when using the device thing, but the problem is that it despawns upon usal, and if it failed, then you have to abandon the quest, exit Gnomeregan, go back to Kharanas and retake the quest. I can't believe that this was ever intended. I'm pretty sure the item isn't supposed to disappear unless you successfully get the fallout.

**Comment by hribsatan** [comment]
quest still bugged you dont get quest item after use vial on slimes
