### ISSUE TITLE
[Quests] Engineering Specialization

### ISSUE THREAD

**Issue by Phatcat** [ServerProject/Phoenix_1.12.1_Issue_tracker#2717]
Alright, I'll try to report this as clean as possible, and with the right information so the ticket won't be closed again.

As I was explained in the ticket that's been closed, the level requirement for the engineering specialization quests is level 30. I don't see any reason or information anywhere as to why this would be untrue, but I'd like to contest where Emerald Dream gets their information? 
Is it from aowow.org? 'Cause if that is the case, then this might be worth taking a look at:

http://www.aowow.org/?quests=5.-201

Start by looking at the three "Show Your Work" quests (one for Horde Gnomish, one for Ally Gnomish and one for cross-faction Goblin) - Hordes aren't allowed to pick Gnomish Engineering before level 46?

Also, Notice the "Goblin Engineering" quest level 47, compared to "Gnome Engineering" quest level 47. 
Goblin Engineering only requires level 30 whilst Gnomish requires level 47.

You may also want to notice that the three "Pledge of Secrecy" quests all have different level requirements.

Furthermore, Membership Card Renewal requirement shouldn't be any higher than "Show Your Work" as it seems very weird and wrong, being unable to renew your membership card for 17 levels.

How it works on the server: The Engineering trainer in Ironforge thinks you're too low level to start any quest, even as high as level 40, which leads me to believe that the values on the server might have come from aowow.org. At the same level, the Engineerirng trainer in Stormwind City only have the quest "Goblin Engineering" available. (This might have been intended, though - Does anyone remember if you had to go to Ironforge to start the Gnomish Engineering quest, or if you could do it in Stormwind also?)

The only guy who seemed to be working as he should was the Engineering trainer in Ratchet who will let you choose both quests. (I don't know if they were available at level 30, as I visited him at level 40) - After obtaining the quest from Ratchet, I was able to complete the whole chain with no further complications. I have, however, not seen the quest "Membership Card Renewal" anywhere, which could point to this quest's level requirement being wrong too.

How I believe it should work:
The "Show Your Work" quests should all have a level 30 requirement only, as well as the first part of "Gnome Engineering" and "Goblin Engineering" since they're the prequests to "Show Your Work".
"The Pledge of Secrecy" should also only have a level 30 requirement as it's the follow-ups to "Show Your Work" and has be completed to obtain the ability of Gnomish/Goblin Engineering.
Lastly, the quests "Membership Card Renewal" should also be available at level 30 since nothing higher or lower than that would make any sense, what-so-ever.

I will find a source to back me up on this as soon as any developers shows any interest in this bug at all.

Although the quests "Show Your Work" and "The Pledge of Secrecy" might not be bugged at all as I had no trouble completing the chain, the first part of "Gnome Engineering" which is obtained at Ironforge is definitely broken, as it's unobtainable at the desired level. This might also be the case for Goblin Engineering.

I know that a work-around is talking to the trainer in Ratchet, but this should just as well be fixed as it's a very minor bug, but still an annoying one none the less.

**Comment by redmagejoe** [comment]
So why is only the quest for Goblin Engineering from the Gnome in Dwarven District of Stormwind available at 30, while all the others require 47? I'd like to be Gnomish and get my Artisan without waiting until endgame, thanks.
