### ISSUE TITLE
[Hunter] [Spells] Freeze trap activation range too low

### ISSUE THREAD

**Issue by Xsplicit** [ServerProject/Phoenix_1.12.1_Issue_tracker#3346]
Simply put, the way freeze traps are working at the moment, their range of activation is too low compared to how they worked back in Retail.

Here's 2 quick videos displaying their range as of now on Emerald Dream:

http://www.youtube.com/watch?v=0fbbu8VREac
http://www.youtube.com/watch?v=Ux99kh_sIu8

And here is video evidence (time of occurance listed) from several retail PvP videos in which you can clearly see the correct range of Freezing traps:

Kishra: (5:00)  http://www.youtube.com/watch?v=aoxmJgtOLwU
Mustadeo: (7:00)  http://www.youtube.com/watch?v=f5ldwsY9dNE
Rifle Lovin 8 (14:50, 24:00)  http://www.youtube.com/watch?v=dPtSiKS5lJw
Ranger (0:06, 0:54, 5:25)  http://www.youtube.com/watch?v=4ui6mf3lHSU
Over 3 (2:32)  http://www.youtube.com/watch?v=fK5a3mBxiFA
Milamber (9:07)  http://www.youtube.com/watch?v=Tu4U_-a2ii0

As i'm sure you know, this ability is very important to hunter PvP, and it is essential it is working correctly for proper class balance. On Emerald Dream currently, the target has to be virtually standing on top of the trap for it to set off, and this is not how it was intended. I didn't test the range of any other traps, but i'm assuming the same problem exists with them also.

**Comment by Skylarz** [comment]
Is this ever planned to be fixed?
2 years have passed since Xsplicit posted this issue without any change or feedback and it's among top 3 hunter bugs, while some trivial things like ammo consumation on use instead of hit got fixed within a week :D

**Comment by Nzzoth** [comment]
Fixed, coming soon on PTR.

**Comment by anaaz** [comment]
Fix applied to Live on 23/06/2016 Patch 12
