### ISSUE TITLE
[Warlock] shadow trance

### ISSUE THREAD

**Issue by tal4562** [ServerProject/Phoenix_1.12.1_Issue_tracker#4386]
according to affliction talent tree there should be 4% chance to proc shadow trance on
corruption and drain life ticks 
http://database.wow-one.com/index.php?spell=18095
proc chance is much higher
i made a test with lvl 60 priest and lock. lock casts corruption evrey 18 seconds for the duration of 268 seconds corruption ticks every 3 seconds thus making 89 ticks
i got 15 shadow trance procs from that which are 18.85% as seens the the screen shot here http://i57.tinypic.com/2wch09c.png
if needed ill make another test with longer duration once ill have more time
edit i have made a longer test:
http://oi61.tinypic.com/5chhl.jpg 935 seconds are 311.667 ticks
with 52 procs the proc chance is 16.684%

**Comment by ivid** [comment]
Fixed, coming soon on PTR.

**Comment by anaaz** [comment]
Fix applied to live, 23/06/2015 Patch 12
